version: '2'
services:
    colorima-app:
        image: colorima
            - colorima-mariadb:mariadb
        environment:
            - SPRING_PROFILES_ACTIVE=prod
            - SPRING_DATASOURCE_URL=jdbc:mariadb://mariadb:3306/colorima
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 8080:8080
    colorima-mariadb:
        extends:
            file: mariadb.yml
            service: colorima-mariadb
