version: '2'
services:
    colorima-mariadb:
        container_name: colorima-mariadb
        image: mariadb:10.1.16
        # volumes:
        #     - ~/volumes/jhipster/colorima/mysql/:/var/lib/mysql/
        environment:
            - MYSQL_USER=root
            - MYSQL_ALLOW_EMPTY_PASSWORD=yes
            - MYSQL_DATABASE=colorima
        ports:
            - 3306:3306
